CREATE TABLE streamer_services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    streamer_id INT NOT NULL,
    service_key VARCHAR(64) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NULL,
    service_type VARCHAR(32) NOT NULL,
    media_kind VARCHAR(32) NULL,
    media_url TEXT NULL,
    duration_ms INT NULL,
    price INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_member_id INT NULL,
    updated_by_member_id INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_streamer_service_key (streamer_id, service_key),
    INDEX idx_streamer_services_streamer_enabled (streamer_id, enabled),
    FOREIGN KEY (streamer_id) REFERENCES streamers(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_member_id) REFERENCES members(id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by_member_id) REFERENCES members(id) ON DELETE SET NULL,
    CHECK (price >= 0),
    CHECK (duration_ms IS NULL OR (duration_ms >= 1000 AND duration_ms <= 15000))
);
